export type Language = 'nl' | 'en';

export const geoTranslations: Record<string, string> = {
  // Countries
  "Albanië": "Albania",
  "Algerije": "Algeria",
  "Argentinië": "Argentina",
  "Australië": "Australia",
  "België": "Belgium",
  "Bosnië en Herzegovina": "Bosnia and Herzegovina",
  "Brazilië": "Brazil",
  "Bulgarije": "Bulgaria",
  "Chili": "Chile",
  "Cyprus": "Cyprus",
  "Cyprus (Eiland)": "Cyprus (Island)",
  "D.R. Congo": "D.R. Congo",
  "Denemarken": "Denmark",
  "Duitsland": "Germany",
  "Egypte": "Egypt",
  "Estland": "Estonia",
  "Ethiopië": "Ethiopia",
  "Filipijnen": "Philippines",
  "Finland": "Finland",
  "Frankrijk": "France",
  "Griekenland": "Greece",
  "Hongarije": "Hungary",
  "IJsland": "Iceland",
  "IJsland (Eiland)": "Iceland (Island)",
  "Ierland": "Ireland",
  "India": "India",
  "Indonesië": "Indonesia",
  "Irak": "Iraq",
  "Iran": "Iran",
  "Israël": "Israel",
  "Italië": "Italy",
  "Ivoorkust": "Ivory Coast",
  "Japan": "Japan",
  "Jordanië": "Jordan",
  "Kenia": "Kenya",
  "Kroatië": "Croatia",
  "Letland": "Latvia",
  "Libanon": "Lebanon",
  "Libië": "Libya",
  "Litouwen": "Lithuania",
  "Luxemburg": "Luxembourg",
  "Marokko": "Morocco",
  "Mexico": "Mexico",
  "Mexico Stad": "Mexico City",
  "Moldavië": "Moldova",
  "Montenegro": "Montenegro",
  "Nederland": "Netherlands",
  "Noord-Macedonië": "North Macedonia",
  "Noord-Maka": "North Macedonia",
  "Noorwegen": "Norway",
  "Oekraïne": "Ukraine",
  "Oostenrijk": "Austria",
  "Pakistan": "Pakistan",
  "Polen": "Poland",
  "Portugal": "Portugal",
  "Roemenië": "Romania",
  "Rusland": "Russia",
  "Rusland (Europees deel)": "Russia (European part)",
  "Rwanda": "Rwanda",
  "Saudi-Arabië": "Saudi Arabia",
  "Servië": "Serbia",
  "Slovenië": "Slovenia",
  "Slowakije": "Slovakia",
  "Soedan en Zuid-Soedan": "Sudan and South Sudan",
  "Somalië": "Somalia",
  "Spanje": "Spain",
  "Syrië": "Syria",
  "Thailand": "Thailand",
  "Tsjechië": "Czechia",
  "Tunesië": "Tunisia",
  "Turkije": "Turkey",
  "Venezuela": "Venezuela",
  "Verenigd Koninkrijk": "United Kingdom",
  "Verenigde Staten": "United States",
  "Wit-Rusland": "Belarus",
  "Zuid-Afrika": "South Africa",
  "Zweden": "Sweden",
  "Zwitserland": "Switzerland",

  // Capitals & Major Cities
  "Aarlen": "Arlon",
  "Addis Abeba": "Addis Ababa",
  "Algiers": "Algiers",
  "Athene": "Athens",
  "Bagdad": "Baghdad",
  "Beijing": "Beijing",
  "Beiroet": "Beirut",
  "Belgrado": "Belgrade",
  "Berlijn": "Berlin",
  "Boedapest": "Budapest",
  "Boekarest": "Bucharest",
  "Brugge": "Bruges",
  "Brussel": "Brussels",
  "Brussels Hoofdstedelijk Gewest": "Brussels-Capital Region",
  "Cairo": "Cairo",
  "Jeruzalem": "Jerusalem",
  "Kaapstad": "Cape Town",
  "Khartoem": "Khartoum",
  "Kiev": "Kyiv",
  "Kigali": "Kigali",
  "Kolkata/Calcutta": "Kolkata",
  "Kopenhagen": "Copenhagen",
  "Damascus": "Damascus",
  "Gent": "Ghent",
  "Leuven": "Louvain",
  "Lissabon": "Lisbon",
  "Londen": "London",
  "Luik": "Liège",
  "Manilla": "Manila",
  "Moskou": "Moscow",
  "Parijs": "Paris",
  "Praag": "Prague",
  "Riyad": "Riyadh",
  "Rome": "Rome",
  "Teheran": "Tehran",
  "Tokio": "Tokyo",
  "Warschau": "Warsaw",
  "Washington DC": "Washington, D.C.",
  "Wenen": "Vienna",

  // Belgian Regions, Ports & Provinces
  "Antwerpen": "Antwerp",
  "Vlaams Gewest": "Flemish Region",
  "Waals Gewest": "Walloon Region",
  "Vlaanderen": "Flanders",
  "Wallonië": "Wallonia",
  "Oost-Vlaanderen": "East Flanders",
  "West-Vlaanderen": "West Flanders",
  "Vlaams-Brabant": "Flemish Brabant",
  "Waals-Brabant": "Walloon Brabant",
  "Limburg": "Limburg",
  "Henegouwen": "Hainaut",
  "Namen": "Namur",
  "Waver": "Wavre",
  "Port of Antwerpen": "Port of Antwerp",
  "Port of Gent": "Port of Ghent",
  "Port of Zeebrugge": "Port of Zeebrugge",

  // Continents, Regions & Islands
  "Afrika": "Africa",
  "Amerika": "Americas",
  "Noord-Amerika": "North America",
  "Zuid-Amerika": "South America",
  "Antarctica": "Antarctica",
  "Azië": "Asia",
  "Europa": "Europe",
  "Eurazië": "Eurasia",
  "Oceanië": "Oceania",
  "Britse Eilanden": "British Isles",
  "Iberisch Schiereiland": "Iberian Peninsula",
  "Italiaans Schiereiland": "Italian Peninsula",
  "Scandinavië": "Scandinavia",
  "Balkan": "Balkans",
  "Corsica": "Corsica",
  "Sardinië": "Sardinia",
  "Sicilië": "Sicily",
  "Kreta": "Crete",

  // Oceans & Seas
  "Adriatische Zee": "Adriatic Sea",
  "Atlantische Oceaan": "Atlantic Ocean",
  "Egeïsche Zee": "Aegean Sea",
  "Grote Oceaan": "Pacific Ocean",
  "Indische Oceaan": "Indian Ocean",
  "Ionische Zee": "Ionian Sea",
  "Ierse Zee": "Irish Sea",
  "Kaspische Zee": "Caspian Sea",
  "Middellandse Zee": "Mediterranean Sea",
  "Noordelijke IJszee": "Arctic Ocean",
  "Noordzee": "North Sea",
  "Oostzee": "Baltic Sea",
  "Tyrreense Zee": "Tyrrhenian Sea",
  "Zwarte Zee": "Black Sea",
  "Het Kanaal": "English Channel",
  "Straat van Gibraltar": "Strait of Gibraltar",
  "Bosporus": "Bosphorus",

  // Rivers & Waterways
  "Amazone": "Amazon",
  "Dnjepr": "Dnieper",
  "Donau": "Danube",
  "IJzer": "Yser",
  "Jangtsekiang": "Yangtze",
  "Kongo": "Congo",
  "Leie": "Lys",
  "Maas": "Meuse",
  "Nijl": "Nile",
  "Rijn": "Rhine",
  "Samber": "Sambre",
  "Schelde": "Scheldt",
  "Theems": "Thames",
  "Weichsel": "Vistula",
  "Wolga": "Volga",

  // Mountains & High Grounds
  "Alpen": "Alps",
  "Coast Range (Kustgebergte)": "Coast Range",
  "Ethiopisch Hoogland": "Ethiopian Highlands",
  "Hoogland van Iran": "Iranian Plateau",
  "Hoogland van Tibet": "Tibetan Plateau",
  "Karpaten": "Carpathians",
  "Kaukasus": "Caucasus",
  "Oeral": "Ural Mountains",
  "Oost-Afrikaans Hoogland": "East African Highlands",
  "Pyreneeën": "Pyrenees",
  "Scandinavisch Hoogland": "Scandinavian Mountains",
  "Taurus": "Taurus Mountains",

  // Reference Lines & Other Landmarks
  "Evenaar": "Equator",
  "Kreeftskeerkring": "Tropic of Cancer",
  "Noordpoolcirkel": "Arctic Circle",
  "Nulmeridiaan": "Prime Meridian",
  "Steenbokskeerkring": "Tropic of Capricorn",
  "Zuidpoolcirkel": "Antarctic Circle"
};

// Create reverse translations for English to Dutch lookup
export const reverseGeoTranslations: Record<string, string> = {
  "USA": "Verenigde Staten",
  "United States of America": "Verenigde Staten",
  "United States": "Verenigde Staten",
  "Great Britain": "Verenigd Koninkrijk",
  "UK": "Verenigd Koninkrijk",
  "Czech Republic": "Tsjechië",
  "Côte d'Ivoire": "Ivoorkust",
  "Ivory Coast": "Ivoorkust",
  "Türkiye": "Turkije",
  "Turkey": "Turkije",
  "Russian Federation": "Rusland",
  "Bosnia and Herz.": "Bosnië en Herzegovina",
  "Democratic Republic of the Congo": "D.R. Congo",
  "Dem. Rep. Congo": "D.R. Congo",
  "Congo": "D.R. Congo",
  "Central African Rep.": "Centraal-Afrikaanse Republiek",
  "Dominican Rep.": "Dominicaanse Republiek",
  "Equatorial Guinea": "Equatoriaal-Guinea"
};

// Auto-populate reverse lookup from geoTranslations (Dutch -> English)
Object.entries(geoTranslations).forEach(([nl, en]) => {
  reverseGeoTranslations[en] = nl;
  reverseGeoTranslations[en.toLowerCase()] = nl;
});

/**
 * Translates a given name according to the target language.
 */
export function translateName(name: string | null | undefined, lang: Language): string {
  if (!name) return '';
  if (lang === 'nl') {
    return reverseGeoTranslations[name] || reverseGeoTranslations[name.toLowerCase()] || name;
  }
  return geoTranslations[name] || name;
}

/**
 * Common exercise prompt templates in NL and EN.
 */
export const uiTranslations = {
  nl: {
    languageName: "Nederlands",
    flagQuizTitle: "Landvlag Herkennen",
    flagQuizQuestion: "Van welk land is deze vlag?",
    capitalQuestion: (country: string) => `Wat is de hoofdstad van ${country}?`,
    countryFromCapitalQuestion: (capital: string) => `Welk land hoort bij de hoofdstad ${capital}?`,
    inWhichProvinceQuestion: (city: string) => `In welke provincie ligt ${city}?`,
    clickOnMapQuestion: (name: string) => `Klik op de kaart: ${name}`,
    selectAnswer: "Selecteer het juiste antwoord:",
    questionLabel: "Vraag",
    correctLabel: "Juist",
    answeredLabel: "Beantwoord",
    settingsTitle: "Applicatie Instellingen",
    languageSettingTitle: "Taal van Benamingen",
    languageSettingSubtitle: "Kies of alle namen en vragen in het Nederlands of Engels worden weergegeven",
    toastLangChanged: (lang: string) => `Taal ingesteld op ${lang}`,
    
    // Navigation
    navHome: "Home",
    navDashboard: "Dashboard",
    navStats: "Statistieken",
    navSettings: "Instellingen",
    navAdmin: "Beheer",
    navDebug: "Debugger",
    navMyLearning: "Mijn Leerstof",
    
    // Quiz & Exercises
    backToDashboard: "Terug naar Dashboard",
    exerciseCompleted: "Oefening Afgerond!",
    exerciseCompletedDesc: "Je hebt met succes de geplande sessie afgerond.",
    correctAnswers: "Juiste antwoorden",
    accuracy: "Nauwkeurigheid",
    totalTime: "Totale Tijd",
    newStart: "Nieuwe Start",
    closeMenu: "Menu sluiten",
    loadingMaterial: "Leermateriaal aan het laden...",
    typeAnswerPlaceholder: "Typ je antwoord...",
    submitBtn: "Versturen",
    excellent: "Uitstekend!",
    correctFeedback: "Je antwoord is helemaal correct.",
    wrongFeedback: "Helaas, niet helemaal juist",
    correctAnswerWas: "Het gezochte antwoord was:",
    alternativesLabel: "Alternatieven:",
    questionWord: "VRAAG",
    answerWord: "ANTWOORD",
    tapToReveal: "Tik op de kaart om het antwoord te zien",
    tapToFlipBack: "Tik om terug te draaien",
    needsReview: "Moet ik herhalen",
    knowThis: "Ken ik wel",
    previous: "Vorige",
    skip: "Sla over",
    categoryLabel: "Categorie",
    noFlagFound: "Geen vlag gevonden",
    
    // Map Quiz Mode
    mapQuizTitle: "Topografische Landkaart Training",
    mapQuizDesc: "Bekijk de landkaart hieronder of klik bovenaan op 'Start Oefening' om te beginnen!",
    currentScore: "Huidige Score",
    chooseRegion: "Kies Regio / Kaart:",
    whatToGuess: "Wat wil je raden?",
    startExercise: "▶ Start Oefening",
    stopExercise: "Stop Oefening",
    mapExerciseActive: "Oefening is Actief — Klik op het juiste object op de kaart",
    interactiveMap: "Interactieve Landkaart",
    clickCapital: "Klik op de hoofdstad:",
    clickHighway: "Klik op de autosnelweg:",
    clickObject: "Klik op het geografisch object:",
    skipQuestion: "Skip vraag",
    
    // Regions
    world: "Wereld",
    europe: "Europa",
    belgium: "België",
    
    // Categories
    catCountries: "Landen",
    catCapitals: "Hoofdsteden",
    catRivers: "Rivieren",
    catProvinces: "Provincies",
    catHighways: "Autosnelwegen",
    catMountains: "Gebergten",
    catFlags: "Vlaggen",

    // My Learning Content
    myLearningTitle: "Mijn Leerstof",
    chooseRegionsTitle: "Kies Regio's",
    chooseSubjectsTitle: "Kies Onderwerpen",
    difficultyTitle: "Moeilijkheidsgraad",
    diffAll: "Alle niveaus",
    diffEasy: "Makkelijk",
    diffMedium: "Gemiddeld",
    diffHard: "Moeilijk",
    startSessionBtn: "Start Oefensessie",
    surpriseMixBtn: "Verrassingsmix"
  },
  en: {
    languageName: "English",
    flagQuizTitle: "Flag Recognition",
    flagQuizQuestion: "Which country does this flag belong to?",
    capitalQuestion: (country: string) => `What is the capital of ${country}?`,
    countryFromCapitalQuestion: (capital: string) => `Which country has the capital ${capital}?`,
    inWhichProvinceQuestion: (city: string) => `In which province is ${city} located?`,
    clickOnMapQuestion: (name: string) => `Click on the map: ${name}`,
    selectAnswer: "Select the correct answer:",
    questionLabel: "Question",
    correctLabel: "Correct",
    answeredLabel: "Answered",
    settingsTitle: "Application Settings",
    languageSettingTitle: "Language for Names",
    languageSettingSubtitle: "Choose whether all names and questions are displayed in Dutch or English",
    toastLangChanged: (lang: string) => `Language set to ${lang}`,
    
    // Navigation
    navHome: "Home",
    navDashboard: "Dashboard",
    navStats: "Statistics",
    navSettings: "Settings",
    navAdmin: "Admin",
    navDebug: "Debugger",
    navMyLearning: "My Learning Content",
    
    // Quiz & Exercises
    backToDashboard: "Back to Dashboard",
    exerciseCompleted: "Exercise Completed!",
    exerciseCompletedDesc: "You have successfully completed the practice session.",
    correctAnswers: "Correct Answers",
    accuracy: "Accuracy",
    totalTime: "Total Time",
    newStart: "Start Again",
    closeMenu: "Close Menu",
    loadingMaterial: "Loading study materials...",
    typeAnswerPlaceholder: "Type your answer...",
    submitBtn: "Submit",
    excellent: "Excellent!",
    correctFeedback: "Your answer is completely correct.",
    wrongFeedback: "Unfortunately, not quite right",
    correctAnswerWas: "The correct answer was:",
    alternativesLabel: "Alternatives:",
    questionWord: "QUESTION",
    answerWord: "ANSWER",
    tapToReveal: "Tap the card to reveal answer",
    tapToFlipBack: "Tap to flip back",
    needsReview: "Needs review",
    knowThis: "I know this",
    previous: "Previous",
    skip: "Skip",
    categoryLabel: "Category",
    noFlagFound: "No flag found",
    
    // Map Quiz Mode
    mapQuizTitle: "Topographic Map Training",
    mapQuizDesc: "View the map below or click 'Start Exercise' at the top to begin!",
    currentScore: "Current Score",
    chooseRegion: "Choose Region / Map:",
    whatToGuess: "What do you want to guess?",
    startExercise: "▶ Start Exercise",
    stopExercise: "Stop Exercise",
    mapExerciseActive: "Exercise is Active — Click on the correct object on the map",
    interactiveMap: "Interactive Map",
    clickCapital: "Click on the capital:",
    clickHighway: "Click on the highway:",
    clickObject: "Click on the geographic object:",
    skipQuestion: "Skip question",
    
    // Regions
    world: "World",
    europe: "Europe",
    belgium: "Belgium",
    
    // Categories
    catCountries: "Countries",
    catCapitals: "Capitals",
    catRivers: "Rivers",
    catProvinces: "Provinces",
    catHighways: "Highways",
    catMountains: "Mountains",
    catFlags: "Flags",

    // My Learning Content
    myLearningTitle: "My Learning Content",
    chooseRegionsTitle: "Choose Regions",
    chooseSubjectsTitle: "Choose Subjects",
    difficultyTitle: "Difficulty Level",
    diffAll: "All levels",
    diffEasy: "Easy",
    diffMedium: "Medium",
    diffHard: "Hard",
    startSessionBtn: "Start Practice Session",
    surpriseMixBtn: "Surprise Mix"
  }
};
